springdoc:
  swagger-ui:
    path: "swagger-ui.html"
  api-docs:
    path: "/api-docs"
spring:
  application:
    name: waste-collection-scheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/wcs
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 161803
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

